public enum MessageType {
    LOGIN_REQUEST,
    USER_DATA,
    LOGIN_ACCEPTED,
    LOGIN_REJECTED,
    USER_JOINED,
    USER_LEFT,
    REGISTRATION_REQUEST, REGISTER_REJECTED, REGISTER_ACCEPTED, TEXT_MESSAGE

}
